name: Release

on:
  push:
    branches: [release/*]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish docker image
    environment: Release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Read version to release from the changelog
        id: next-release
        uses: cucumber/action-changelog@v1.3
        with:
          args: latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          labels: |
            version=${{ steps.next-release.outputs.result }}
          tags: cucumber/cucumber-build:latest,cucumber/cucumber-build:${{ env.version }}
      - uses: cucumber/action-create-github-release@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
